// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core';

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    XmWallet: typeof import('./../src/components/XmWallet')['default'];
    XmSimpleCard: typeof import('./../src/components/XmSimpleCard')['default'];
    // Footer: typeof import('./components/Footer.vue')['default'];
    // README: typeof import('./components/README.md')['default'];
    // RouterLink: typeof import('vue-router')['RouterLink'];
    // RouterView: typeof import('vue-router')['RouterView'];
  }
}

export {};
